all: CPP11.exe

CPP11.exe: clean
	c:\\cygwin\\usr\\local\\bin\\g++ -I/cygdrive/C/Users/gert/git/CPP11/CPP11/include -g3 -O0 -Wall -std=gnu++11 -o CPP11.exe $(wildcard src/*.cpp)


clean:
	c:\\cygwin\\bin\\rm -f CPP11.exe
