all: CPP11.exe

CPP11.exe: clean
	c:\\cygwin\\usr\\local\\bin\\g++ -I/cygdrive/d/Workspace/CPP11/include -g3 -O0 -Wall -std=gnu++11 -o CPP11.exe src/CPP11.cpp


clean:
	c:\\cygwin\\bin\\rm -f CPP11.exe
